[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    adafruit/Adafruit ADS1X15@^2.0.0
    adafruit/RTClib@^2.1.3
    adafruit/Adafruit INA219@^1.2.0
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor